name: CI Pipeline

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, closed ] # Escuchamos ambos momentos

jobs:
  # TRABAJO 1: Se ejecuta MIENTRAS el PR está abierto
  build:
    if: github.event.action != 'closed' # Solo corre si NO se está cerrando
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ejecutar Tests
        run: echo "holaaaaa"

  # TRABAJO 2: Se ejecuta SOLO CUANDO se acepta el PR
  build-and-push-docker:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ejecutar deploy
        run: echo "ya se termino wow"
