name: CI Pipeline

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize ]
  push:
    branches: [ main ]

jobs:
  # TRABAJO 1: Se ejecuta MIENTRAS el PR est√° abierto
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install dependencies
        run: |
          echo "estamos en la rama: $GITHUB_REF_NAME" & npm install
      - name: start app and check health
        if: ${{ github.event_name == 'pull_request' }}
        env:
          PORT: 8080
          NODE_ENV: test
          VARIABLE_ENTORNO: erickolivarok
        run: |
          echo "estamos en la rama: $GITHUB_REF_NAME"
          npm start &
          APP_PID=$!

          sleep 5

          RESPONSE_BODY=$(curl -s http://localhost:8080/health)
          STATUS=$(curl -o /dev/null -s -w "%{http_code}" http://localhost:8080/health)

          echo "codigo de estato http: $STATUS"
          echo "Respuesta del servidor: $RESPONSE_BODY"

          kill $APP_PID

          if [ "$STATUS" -ne 200 ]; then
            echo "Error, el health check fallo"
            exit 1
          fi
          echo "validacion exitosa"
          
      - name: hacer otro test
        #if: success()
        if: ${{ github.event_name == 'pull_request' && success() }}
        run: echo "se ha completado test"

      - name: si algo falla
        #if: failure()
        if: ${{ github.event_name == 'pull_request' && failure() }}
        run: echo "hubo error en el checkeo del test"

      - name: hacer test al push
        if: ${{ github.event_name == 'push' }}
        run: |
          echo "estamos en la rama: $GITHUB_REF_NAME"
          echo "esto se muestra al hacer el push al main solamente"
