name: CI Pipeline

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize ]

jobs:
  # TRABAJO 1: Se ejecuta MIENTRAS el PR está abierto
  build:
    if: github.event_name == 'pull_request' # Solo corre si NO se está cerrando
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ejecutar Tests
        run: echo "holaaaaa"

  # TRABAJO 2: Se ejecuta SOLO CUANDO se acepta el PR
  build-and-push-docker:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ejecutar deploy
        run: echo "ya se termino wow"
